apiVersion: v2
appVersion: 4.0.0
dependencies:
  - name: superset
    repository: https://apache.github.io/superset
    version: 0.12.10
description: Apache Superset is a modern, enterprise-ready business intelligence
  web application
home: https://superset.apache.org/
icon: https://artifacthub.io/image/68c1d717-0e97-491f-b046-754e46f46922@2x
keywords:
  - business intelligence
  - data science
  - okdp
maintainers:
  - email: idir.izitounene@kubotal.io
    name: idirze
    url: https://github.com/idirze
name: superset
sources:
  - https://github.com/apache/superset
  - https://github.com/okdp/charts/tree/main/charts/superset
version: 0.12.10-1.0.0
